# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gamecontrol_pb2 as gamecontrol__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gamecontrol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameControlStub(object):
    """The service block defines what functions we are exposing
    It defines the function name, input message, and output message
    This service block is the contract
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyMatchTicket = channel.unary_unary(
                '/gamecontrol.GameControl/VerifyMatchTicket',
                request_serializer=gamecontrol__pb2.VerifyTicketRequest.SerializeToString,
                response_deserializer=gamecontrol__pb2.VerifyTicketResponse.FromString,
                _registered_method=True)
        self.ReportGameEnd = channel.unary_unary(
                '/gamecontrol.GameControl/ReportGameEnd',
                request_serializer=gamecontrol__pb2.GameEndRequest.SerializeToString,
                response_deserializer=gamecontrol__pb2.GameEndResponse.FromString,
                _registered_method=True)


class GameControlServicer(object):
    """The service block defines what functions we are exposing
    It defines the function name, input message, and output message
    This service block is the contract
    """

    def VerifyMatchTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportGameEnd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyMatchTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyMatchTicket,
                    request_deserializer=gamecontrol__pb2.VerifyTicketRequest.FromString,
                    response_serializer=gamecontrol__pb2.VerifyTicketResponse.SerializeToString,
            ),
            'ReportGameEnd': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportGameEnd,
                    request_deserializer=gamecontrol__pb2.GameEndRequest.FromString,
                    response_serializer=gamecontrol__pb2.GameEndResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gamecontrol.GameControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gamecontrol.GameControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameControl(object):
    """The service block defines what functions we are exposing
    It defines the function name, input message, and output message
    This service block is the contract
    """

    @staticmethod
    def VerifyMatchTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gamecontrol.GameControl/VerifyMatchTicket',
            gamecontrol__pb2.VerifyTicketRequest.SerializeToString,
            gamecontrol__pb2.VerifyTicketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportGameEnd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gamecontrol.GameControl/ReportGameEnd',
            gamecontrol__pb2.GameEndRequest.SerializeToString,
            gamecontrol__pb2.GameEndResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
